-- 코드를 작성해주세요
WITH YEAR_GROUP AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT YEAR(P.DIFFERENTIATION_DATE) AS YEAR, (C.MAX_COLONY - P.SIZE_OF_COLONY) AS YEAR_DEV, P.ID
FROM ECOLI_DATA P
JOIN YEAR_GROUP C
ON YEAR(P.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC